### ISSUE TITLE
Plugin does not detect people anymore

### ISSUE THREAD

**Issue by bxlouis** [zackwag/homebridge-people-guest-mode#3]
I have been using the plugin for quite some time now and it used to work as expected.
However, it suddenly stopped working and I am unable to have it work again.
I tried to roll back to previous version, reinstall the plugin, empty the config directory....

**homebridge-people-guest-mode v0.9.8**

Here is my config:
`        {
            "name": "Guest",
            "people": [
                {
                    "name": "User",
                    "target": "10.0.1.39"
                }
            ],
            "platform": "People"
        }`

Here is the Homebridge log when starting:
_[2/7/2021, 1:53:22 PM] Loaded plugin: homebridge-people-guest-mode@0.9.8
[2/7/2021, 1:53:22 PM] Registering platform 'homebridge-people-guest-mode.People'
[2/7/2021, 1:53:22 PM] Registering accessory 'homebridge-people-guest-mode.PeopleAccessory'
[2/7/2021, 1:53:22 PM] Registering accessory 'homebridge-people-guest-mode.PeopleAllAccessory'
[2/7/2021, 1:53:22 PM] Registering accessory 'homebridge-people-guest-mode.GuestModeSwitch'_
[...]
[2/7/2021, 1:53:22 PM] [Guest] Initializing People platform...
[2/7/2021, 1:53:23 PM] Initializing platform accessory 'Louis'...
[2/7/2021, 1:53:23 PM] Initializing platform accessory 'Guest Mode'...
[2/7/2021, 1:53:23 PM] Initializing platform accessory 'Anyone'...
[2/7/2021, 1:53:23 PM] [Guest] WebHook: Started server on port '51828'.
[...]

After that, nothing in the log about the platform, although I have a Samsung Galaxy correctly connected to my LAN, with a DHCP reservation on 10.0.1.39. I tried with multiple different devices without any success.

All sensors, along with the "Guest" switch are correctly displayed in the Home app. Switching the "Guest" switch on correctly triggers the "Anyone" sensors on, but the "Users" people sensors remain silent. 

My forme configuration included `threshold`, `pingInterval`, `ignoreReEnterExitSeconds` and `cacheDirectory` but I removed them to debug. 

I'm not sure how I could gather more information in order to debug. It might come from my setup but everything on my LAN works perfectly. 

Note that I am using Homebridge with Docker and with a Traefik2 reverse proxy - but I'm not sure how it could affect the plugin as everything else works flawless.

**Comment by zackwag** [comment]
@bxlouis did you switch to a Docker instance recently? Sometimes `ping` is not installed by default in Docker.

There is more information about this in the issues for the plugin I forked:
https://github.com/PeteLawrence/homebridge-people/issues/90

**Comment by bxlouis** [comment]
Hi @zackwag thanks for getting back to me! My setup used to work on the same environment.
I just ssh my NAS and tried `sudo ping 10.0.1.39` :

PING 10.0.1.39 (10.0.1.39) 56(84) bytes of data.
64 bytes from 10.0.1.39: icmp_seq=1 ttl=64 time=178 ms
64 bytes from 10.0.1.39: icmp_seq=2 ttl=64 time=789 ms
64 bytes from 10.0.1.39: icmp_seq=3 ttl=64 time=578 ms
64 bytes from 10.0.1.39: icmp_seq=4 ttl=64 time=396 ms
64 bytes from 10.0.1.39: icmp_seq=5 ttl=64 time=216 ms
64 bytes from 10.0.1.39: icmp_seq=6 ttl=64 time=35.2 ms
64 bytes from 10.0.1.39: icmp_seq=7 ttl=64 time=700 ms
64 bytes from 10.0.1.39: icmp_seq=8 ttl=64 time=490 ms
64 bytes from 10.0.1.39: icmp_seq=9 ttl=64 time=309 ms

However, when trying `ping 10.0.1.39`, I got 
ping: socket: Operation not permitted
ping: socket: Operation not permitted

Could this be the issue as the homebridge container runs using a "docker" user, which is not root?

**Comment by zackwag** [comment]
That sounds very possible to me. I'm not running HB in a docker container, so I can't figure out more than that.

I will say that someone posted a solution to this problem in the issue I linked:
https://github.com/PeteLawrence/homebridge-people/issues/90#issuecomment-687350296

Basically ping requires root access for raw sockets and regular users don't have access. The command in the linked comment alters the permissions and allows regular users to have the raw socket capability: https://wiki.archlinux.org/index.php/capabilities
