### ISSUE TITLE
Setting up the plugin with Homebridge-X-UI registers it as "Accessory" and not "Platform"

### ISSUE THREAD

**Issue by bxlouis** [zackwag/homebridge-people-guest-mode#4]
I tried to reinstall and setup the plugin using the Homebridge-X-UI interface.
The plugin was added under the "Accessory" section and not the "Platform" one.
Also, Homebridge complained that the config lacked the "name" attribute which is mandatory.

**Comment by zackwag** [comment]
@bxlouis I just updated the plugin to include a `name` property for the plugin.

https://github.com/zackwag/homebridge-people-guest-mode/pull/5/commits/06432f84b5e1a0f1996bb31319dce01430aa3683

I'm not sure why it registered under `accessory` for you as it is set to `"pluginType": "platform"` in the `config.schema.json`

The end result on a fresh install with this new config is the settings of 

```json
{
  "platforms": [
    {
      "name": "Homebridge People Guest Mode",
      "people": [
        {
          "name": "Zack",
          "target": "10.0.0.77"
        }
      ],
      "platform": "People"
    }
  ]
}
```
